# Generated by Django 3.1 on 2021-02-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210131_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='asin',
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.URLField(),
        ),
    ]
